//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsignmentSettlementDetail
    {
        public long Id { get; set; }
        public string ConsignmentNo { get; set; }
        public long TransactionDetailId { get; set; }
    }
}
