//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInHeader
    {
        public StockInHeader()
        {
            this.StockInDetails = new HashSet<StockInDetail>();
        }
    
        public long id { get; set; }
        public string StockCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FromShopId { get; set; }
        public Nullable<int> ToShopId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual Shop Shop1 { get; set; }
        public virtual ICollection<StockInDetail> StockInDetails { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
